# Generated by Django 2.1.15 on 2023-09-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinfo',
            name='user',
            field=models.IntegerField(max_length=20),
        ),
    ]
