# Generated by Django 2.1.15 on 2023-09-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230905_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinfo',
            name='user',
            field=models.IntegerField(),
        ),
    ]
