# Generated by Django 2.1.15 on 2023-09-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20230910_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
