# Generated by Django 2.1.15 on 2023-09-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230911_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='description',
            field=models.TextField(),
        ),
    ]
