# Generated by Django 2.1.15 on 2023-09-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_cancelledorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancelledorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='cancelledorder',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='CancelledOrder',
        ),
    ]
