# Generated by Django 2.1.15 on 2023-09-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20230918_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinfo',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
