# Generated by Django 2.1.15 on 2023-09-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20230913_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
