# Generated by Django 2.1.15 on 2023-09-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20230922_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='ratings',
            field=models.IntegerField(null=True),
        ),
    ]
