# Generated by Django 2.1.15 on 2023-09-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_productinfo_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='ratings',
            field=models.IntegerField(default=5, null=True),
        ),
    ]
