# Generated by Django 2.1.15 on 2023-09-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20230923_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='ratings',
            field=models.FloatField(default=5, null=True),
        ),
    ]
