# Generated by Django 2.1.15 on 2023-09-27 06:19

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20230923_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default=main.models.random_string, max_length=50),
        ),
    ]
