# Generated by Django 2.1.15 on 2023-09-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
