# Generated by Django 2.1.15 on 2023-09-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_transaction_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_rated',
            field=models.BooleanField(null=True),
        ),
    ]
