# Generated by Django 2.1.15 on 2023-10-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20231002_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
